// userConstants.js

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_CLEAR_ERRORS = 'USER_REGISTER_CLEAR_ERRORS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAIL = 'USER_DATA_FAIL';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_TEMP_USER_ID = 'SET_TEMP_USER_ID';
export const CLEAR_TEMP_USER_ID = 'CLEAR_TEMP_USER_ID';
export const FETCH_USER_ID_REQUEST = 'FETCH_USER_ID_REQUEST';
export const FETCH_USER_ID_SUCCESS = 'FETCH_USER_ID_SUCCESS';
export const FETCH_USER_ID_FAIL = 'FETCH_USER_ID_FAIL';
export const SET_SCHWAB_AUTHENTICATION = 'SET_SCHWAB_AUTHENTICATION';
export const CHECK_SCHWAB_AUTH_STATUS = 'CHECK_SCHWAB_AUTH_STATUS';
export const SET_ONBOARDING_STATUS = 'SET_ONBOARDING_STATUS';

// Add these to userConstants.js
export const UPDATE_USER_SUBSCRIPTION_REQUEST = 'UPDATE_USER_SUBSCRIPTION_REQUEST';
export const UPDATE_USER_SUBSCRIPTION_SUCCESS = 'UPDATE_USER_SUBSCRIPTION_SUCCESS';
export const UPDATE_USER_SUBSCRIPTION_FAIL = 'UPDATE_USER_SUBSCRIPTION_FAIL';

export const FETCH_CHAT_RESPONSE_COUNT_REQUEST = 'FETCH_CHAT_RESPONSE_COUNT_REQUEST';
export const FETCH_CHAT_RESPONSE_COUNT_SUCCESS = 'FETCH_CHAT_RESPONSE_COUNT_SUCCESS';
export const FETCH_CHAT_RESPONSE_COUNT_FAIL = 'FETCH_CHAT_RESPONSE_COUNT_FAIL';
export const UPDATE_LOCAL_CHAT_RESPONSE_COUNT = 'UPDATE_LOCAL_CHAT_RESPONSE_COUNT';
